version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: aviaite-postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data